# Generated by Django 3.1.4 on 2022-06-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_alter_agent_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
