# Generated by Django 3.1.4 on 2022-06-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_followup_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='reminder',
            new_name='reminder_date',
        ),
        migrations.AddField(
            model_name='followup',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
