# Generated by Django 3.1.4 on 2022-06-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('leads', '0027_auto_20220613_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='followup',
            name='reminder',
            field=models.ManyToManyField(related_name='follow_up_reminders', to='schedule.Schedule'),
        ),
    ]
