# Generated by Django 3.1.4 on 2022-06-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_auto_20220613_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='reminder',
        ),
    ]
