# Generated by Django 3.1.4 on 2022-06-16 13:17

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_auto_20220616_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(default=leads.models.get_default_category, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.category'),
        ),
    ]
