# Generated by Django 3.1.4 on 2022-06-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_auto_20220616_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='organisation',
        ),
        migrations.AddField(
            model_name='category',
            name='organisation',
            field=models.ManyToManyField(to='leads.UserProfile'),
        ),
    ]
