# Generated by Django 3.1.4 on 2022-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_auto_20220616_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadssheet',
            name='random',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
