# Generated by Django 3.1.4 on 2022-06-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_remove_followup_reminder'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='followup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_reminder', to='leads.followup'),
            preserve_default=False,
        ),
    ]
