# Generated by Django 3.1.4 on 2022-06-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_remove_followup_reminder'),
        ('schedule', '0002_schedule_followup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='followup',
        ),
        migrations.AddField(
            model_name='schedule',
            name='lead',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='lead_reminder', to='leads.lead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
