# Generated by Django 3.1.4 on 2022-06-14 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_remove_followup_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0004_auto_20220613_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_reminder', to='leads.lead'),
        ),
        migrations.CreateModel(
            name='ReminderNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=30)),
                ('reminder_on', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reminder_on'],
            },
        ),
    ]
